/**
 * THE LADDER IS A DECISION; THE MANIFEST IS A FACT. This holds them to
 * each other, and both to the files on disk.
 *
 * `textureQuality.ts` says there are five rungs and what each is for.
 * `textureManifest.ts` is generated by `npm run bake:textures` and says
 * what was actually baked. They are deliberately not the same list — a
 * master smaller than a rung is not baked to that rung — so the useful
 * question is not "are they equal" but "is every fact the manifest
 * states true, and reachable".
 *
 * Three ways this could rot, and a test each:
 *
 *  1. THE MANIFEST NAMES A FILE THAT IS NOT THERE. The generated module
 *     is committed and the `.webp` files are committed beside it; a
 *     rebase, a partial `git add` or a `.gitignore` could separate them,
 *     and the failure in the game is a texture that silently never
 *     loads.
 *  2. THE MANIFEST DRIFTS FROM THE LADDER. Someone edits a rung's size
 *     in `textureQuality.ts` and does not re-run the bake, so the game
 *     asks for `water-normal.640.webp` forever.
 *  3. SOMEONE EDITS THE GENERATED FILE. It says DO NOT EDIT; this is
 *     what makes that more than a request, by checking the numbers
 *     against the bytes.
 *
 * The size assertions are read from the actual files rather than typed,
 * so re-arting a texture does not need this file edited — only re-baked.
 */
import { readFileSync, existsSync, statSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import {
  BAKED_TEXTURES, TEXTURE_DIR, bakedTexture, textureSizeFor, textureUrl,
} from '../src/assets/textureManifest';
import {
  MOBILE_TIERS, TEXTURE_QUALITY, TEXTURE_TIERS, textureBytes, type TextureTier,
} from '../src/assets/textureQuality';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const PUBLIC = path.join(ROOT, 'public');
const RUNG_SIZES = TEXTURE_TIERS.map((tier) => TEXTURE_QUALITY[tier].size);

/**
 * The RIFF chunks of a WebP, by fourcc.
 *
 * A WebP is not one shape. A plain lossy file is `VP8 `, a plain
 * lossless one is `VP8L`, and ANYTHING WITH ALPHA is wrapped in the
 * extended container `VP8X` with the codec chunk nested inside it — so
 * reading the fourcc at offset 12 and calling it the codec is right for
 * the foam and wrong for every normal map, which all carry alpha.
 */
function webpChunks(file: string): Map<string, { offset: number; length: number }> {
  const bytes = readFileSync(file);
  expect(bytes.subarray(0, 4).toString('ascii'), `${file} is not RIFF`).toBe('RIFF');
  expect(bytes.subarray(8, 12).toString('ascii'), `${file} is not WEBP`).toBe('WEBP');
  const chunks = new Map<string, { offset: number; length: number }>();
  let at = 12;
  while (at + 8 <= bytes.length) {
    const fourcc = bytes.subarray(at, at + 4).toString('ascii');
    const length = bytes.readUInt32LE(at + 4);
    chunks.set(fourcc, { offset: at + 8, length });
    // VP8X is a header chunk: the image chunks follow it rather than
    // sitting inside its payload.
    at += 8 + length + (length % 2);
  }
  return chunks;
}

/** `VP8L` for lossless, `VP8 ` for lossy — whichever container it arrived in. */
function webpCodec(file: string): string {
  const chunks = webpChunks(file);
  if (chunks.has('VP8L')) return 'VP8L';
  if (chunks.has('VP8 ')) return 'VP8 ';
  throw new Error(`${file}: no VP8L or VP8 chunk — found ${[...chunks.keys()].join(', ')}`);
}

/** The dimensions the file itself claims. Read them, do not trust the filename. */
function webpSize(file: string): { width: number; height: number } {
  const bytes = readFileSync(file);
  const chunks = webpChunks(file);
  const extended = chunks.get('VP8X');
  if (extended) {
    const o = extended.offset + 4; // 4 bytes of flags, then 3-byte width-1, 3-byte height-1.
    return {
      width: (bytes[o] | (bytes[o + 1] << 8) | (bytes[o + 2] << 16)) + 1,
      height: (bytes[o + 3] | (bytes[o + 4] << 8) | (bytes[o + 5] << 16)) + 1,
    };
  }
  const lossless = chunks.get('VP8L');
  if (lossless) {
    // 14 bits of width-1 then 14 of height-1, after the 0x2f signature.
    const bits = bytes.readUInt32LE(lossless.offset + 1);
    return { width: (bits & 0x3fff) + 1, height: ((bits >> 14) & 0x3fff) + 1 };
  }
  const lossy = chunks.get('VP8 ');
  if (lossy) {
    // The key-frame header: 3-byte tag, the 3-byte start code, then the size.
    const o = lossy.offset + 6;
    return { width: bytes.readUInt16LE(o) & 0x3fff, height: bytes.readUInt16LE(o + 2) & 0x3fff };
  }
  throw new Error(`${file}: no image chunk`);
}

describe('the manifest describes files that exist', () => {
  it('bakes something at all — an empty manifest would pass every other test here', () => {
    expect(BAKED_TEXTURES.length).toBeGreaterThan(0);
    for (const texture of BAKED_TEXTURES) expect(texture.sizes.length).toBeGreaterThan(0);
  });

  it('has every file it claims, at the size the name promises', () => {
    for (const texture of BAKED_TEXTURES) {
      for (const size of texture.sizes) {
        const file = path.join(PUBLIC, TEXTURE_DIR, `${texture.name}.${size}.webp`);
        expect(existsSync(file), `missing ${path.relative(ROOT, file)} — run npm run bake:textures`).toBe(true);
        expect(statSync(file).size).toBeGreaterThan(0);
        // The name is a claim about the pixels. Check the pixels.
        expect(webpSize(file), path.relative(ROOT, file)).toEqual({ width: size, height: size });
      }
    }
  });

  it('encodes normal maps losslessly and colour maps lossily', () => {
    // The reason this is a per-texture KIND: lossy WebP is YUV 4:2:0, so
    // it stores a normal map's x and y at half resolution and turns the
    // decoded normals by about six degrees. `VP8L` is the lossless chunk;
    // `VP8 ` is the lossy one. The bake proves the round trip, and this
    // proves the bake used the encoder it said it did.
    for (const texture of BAKED_TEXTURES) {
      for (const size of texture.sizes) {
        const file = path.join(PUBLIC, TEXTURE_DIR, `${texture.name}.${size}.webp`);
        const want = texture.kind === 'normal' ? 'VP8L' : 'VP8 ';
        expect(webpCodec(file), `${texture.name}.${size} is ${texture.kind}`).toBe(want);
      }
    }
  });
});

describe('the manifest agrees with the ladder', () => {
  it('bakes only rungs the ladder defines', () => {
    for (const texture of BAKED_TEXTURES) {
      for (const size of texture.sizes) {
        expect(RUNG_SIZES, `${texture.name} has a ${size} that is not a rung`).toContain(size);
      }
    }
  });

  it('never bakes above the master, and never skips a rung below it', () => {
    // Upscaling invents pixels and then charges the GPU four times the
    // memory for them. Skipping a rung the master could reach would leave
    // a tier quietly running a coarser texture than it asked for.
    for (const texture of BAKED_TEXTURES) {
      const reachable = RUNG_SIZES.filter((size) => size <= texture.masterSize).sort((a, b) => a - b);
      expect([...texture.sizes], texture.name).toEqual(reachable);
    }
  });

  it('starts at the coarsest rung, which is what makes the clamp downward', () => {
    // `textureSizeFor` walks down from the tier's rung. That can only be
    // a walk DOWN if the coarsest rung is always present — the bake
    // refuses a master smaller than it, so it always is.
    const coarsest = Math.min(...RUNG_SIZES);
    for (const texture of BAKED_TEXTURES) expect(texture.sizes[0], texture.name).toBe(coarsest);
  });
});

describe('choosing a size for a tier', () => {
  it('gives every tier a real file, including the ones no master reaches', () => {
    for (const texture of BAKED_TEXTURES) {
      for (const tier of TEXTURE_TIERS) {
        const size = textureSizeFor(texture.name, tier);
        expect(texture.sizes, `${texture.name} at ${tier}`).toContain(size);
        expect(size).toBeLessThanOrEqual(TEXTURE_QUALITY[tier].size);
      }
    }
  });

  it('gives ULTRA HIGH the best that exists rather than nothing', () => {
    // water-normal's master is 1536, so its "ultra high" is the 1024 it
    // actually has. A missing texture would be a black ocean; a slightly
    // coarser one is a texture.
    const ripple = bakedTexture('water-normal');
    expect(ripple.masterSize).toBe(1536);
    expect(ripple.sizes).not.toContain(2048);
    expect(textureSizeFor('water-normal', 'ultra-high')).toBe(1024);
  });

  it('never goes down when the tier goes up', () => {
    for (const texture of BAKED_TEXTURES) {
      let last = 0;
      for (const tier of TEXTURE_TIERS) {
        const size = textureSizeFor(texture.name, tier);
        expect(size, `${texture.name} at ${tier}`).toBeGreaterThanOrEqual(last);
        last = size;
      }
    }
  });

  it('builds the URL in one place, honouring the base path', () => {
    expect(textureUrl('water-normal', 'medium')).toBe('/tex/water-normal.512.webp');
    expect(textureUrl('surf-foam', 'ultra-low')).toBe('/tex/surf-foam.128.webp');
    // The game is served from /v1/ on Pages, so the base is not always /.
    expect(textureUrl('surf-foam', 'low', '/v1/')).toBe('/v1/tex/surf-foam.256.webp');
  });
});

describe('what this actually costs a phone', () => {
  it('keeps the ocean’s whole texture budget inside a phone’s at every mobile tier', () => {
    // The number Joshua's complaint is about. v0 ran the ripple map at
    // 1536 — 12.6 MiB on the GPU with its mip chain — plus a 1024 foam,
    // and the audit found three duplicate copies of the pair resident at
    // once. This is the same two textures on the ladder.
    const budget: Record<string, number> = {};
    for (const tier of MOBILE_TIERS) {
      let bytes = 0;
      for (const texture of BAKED_TEXTURES) {
        const side = textureSizeFor(texture.name, tier);
        bytes += Math.round((side * side * 4 * 4) / 3);
      }
      budget[tier] = bytes;
    }
    // Medium — the sensible default for a phone — is the whole ocean in
    // under four megabytes of texture, against v0's eighteen for the same
    // two images.
    expect(budget.medium).toBeLessThan(4 * 1024 * 1024);
    expect(budget['ultra-low']).toBeLessThan(256 * 1024);
    // And the rungs really are a quarter of each other, so the dial has
    // the range the ladder promises.
    expect(budget.medium / budget.low).toBeCloseTo(4, 1);
    expect(budget.high / budget.medium).toBeCloseTo(4, 1);
    // The 1536 v0 shipped, for one of the two textures alone.
    const v0Ripple = Math.round((1536 * 1536 * 4 * 4) / 3);
    expect(v0Ripple / budget.medium).toBeGreaterThan(4);
  });

  it('agrees with the ladder’s own cost model', () => {
    // `textureBytes` is the ladder's arithmetic; the sum above is the
    // same sum. If they ever disagree, one of them is wrong.
    for (const tier of TEXTURE_TIERS) {
      const side = TEXTURE_QUALITY[tier].size;
      expect(textureBytes(tier)).toBe(Math.round((side * side * 4 * 4) / 3));
    }
  });

  it('downloads less than a megabyte at the tiers a modest phone would pick', () => {
    const wire = (tier: TextureTier): number => BAKED_TEXTURES.reduce((sum, texture) => {
      const size = textureSizeFor(texture.name, tier);
      return sum + statSync(path.join(PUBLIC, TEXTURE_DIR, `${texture.name}.${size}.webp`)).size;
    }, 0);
    expect(wire('ultra-low')).toBeLessThan(64 * 1024);
    expect(wire('low')).toBeLessThan(256 * 1024);
    expect(wire('medium')).toBeLessThan(1024 * 1024);
  });
});
