/**
 * HOW BIG EVERY COUNTED DOWNLOAD IS, in bytes.
 *
 * GENERATED by scripts/bakeSizes.ts — do not edit by hand. Run that
 * script after adding or re-encoding anything the loading screen waits
 * on; tests/assetSizes.test.ts fails if this drifts from public/.
 *
 * It exists so the loading screen can declare a total that is RIGHT in
 * the first frame instead of a guess that lurches as files land. See
 * the script's header for what that looked like.
 *
 * Total: 6.13 MB.
 */
export const ASSET_BYTES: Readonly<Record<string, number>> = {
  'kauai-tex/cliff.jpg': 461843,
  'kauai-tex/grass.jpg': 528690,
  'kauai-tex/jungle.jpg': 472144,
  'kauai-tex/mountain.jpg': 420459,
  'kauai-tex/reef.jpg': 445982,
  'kauai-tex/sand.jpg': 477379,
  'kauai-tex/snow.jpg': 302340,
  'models/queen-winged.glb': 2066824,
  'water-normal.png': 205703,
  'kauai-wet.bin': 1048584,
};

/** What a file weighs, or null if it was not baked. */
export function assetBytes(path: string): number | null {
  return ASSET_BYTES[path] ?? null;
}
