/**
 * WHERE THE HOLE IS, AND WHAT SHAPE THE PICTURE IS.
 *
 * GENERATED by scripts/bakeArt.mjs — do not edit by hand.
 *
 * The splash is the FRONT layer of the bar: a picture with the bar's
 * interior cut out of it. The progress fill goes behind, and only the
 * part of it framed by this hole is ever seen. These fractions are
 * measured off the artwork's alpha channel at bake time, so re-cutting
 * the art moves them with it.
 */
export const SPLASH_WINDOW = {
  left: 0.29053,
  right: 0.71045,
  top: 0.75629,
  bottom: 0.80312,
} as const;

/** The picture's own shape, so the box it sits in matches it exactly. */
export const SPLASH_RATIO = 1.77580;
