/**
 * WHERE THE HOLE IS, AND WHAT SHAPE EACH PICTURE IS.
 *
 * GENERATED by scripts/bakeArt.mjs — do not edit by hand.
 *
 * Each splash is the FRONT layer of the loading bar: a picture with the
 * bar's interior cut out of it. The progress fill goes behind, and only
 * the part of it framed by the hole is ever seen — which is also how
 * the portrait bar gets its rounded ends for nothing. These fractions
 * are measured off each artwork's alpha channel at bake time, so
 * re-cutting the art moves them with it.
 *
 * Two of them because the boot screen appears before anyone has been
 * asked to turn the phone, and a landscape picture on a portrait phone
 * is either letterboxed or cropped to the middle of a tree.
 */
export interface SplashCut {
  /** Filename under the base URL. */
  readonly file: string;
  readonly left: number;
  readonly right: number;
  readonly top: number;
  readonly bottom: number;
  /** Width over height, so the box it sits in matches it exactly. */
  readonly ratio: number;
}

export const SPLASH_LANDSCAPE = {
  file: 'splash.webp',
  left: 0.29053,
  right: 0.71045,
  top: 0.75629,
  bottom: 0.80312,
  ratio: 1.77580,
} as const;

export const SPLASH_PORTRAIT = {
  file: 'splash-portrait.webp',
  left: 0.06348,
  right: 0.93555,
  top: 0.59066,
  bottom: 0.66868,
  ratio: 0.56250,
} as const;

/** The one composed for the shape the screen is now. */
export function splashFor(wide: number, tall: number): SplashCut {
  return wide >= tall ? SPLASH_LANDSCAPE : SPLASH_PORTRAIT;
}
