/**
 * WHERE THE HOLE IS, AND WHAT SHAPE EACH PICTURE IS.
 *
 * GENERATED by scripts/bakeArt.mjs (`npm run bake:art`) — do not edit
 * by hand.
 *
 * Two of them, because the boot screen appears before anyone has been
 * asked to turn the phone and a landscape picture on a portrait phone
 * is either letterboxed or cropped to the middle of a tree. They work
 * differently on purpose:
 *
 *   CUTOUT  the bar's interior is missing from the artwork, so the
 *           picture is the FRONT layer and the fill shows through it.
 *           The rectangle is the bounding box of the art's own alpha.
 *   DRAWN   a plain picture, with the bar built in CSS on top. The
 *           rectangle is placed from where the wordmark actually ends.
 *
 * Either way these are measured at bake time, so new art moves them.
 * Pure data: nothing here touches the DOM, so it can be read anywhere.
 */
export interface SplashCut {
  /** Filename under the base URL. */
  readonly file: string;
  /** Whether the artwork carries the bar, or the bar is drawn on it. */
  readonly kind: 'cutout' | 'drawn';
  /** The bar's rectangle, as fractions of the picture's width and height. */
  readonly left: number;
  readonly right: number;
  readonly top: number;
  readonly bottom: number;
  /** Width over height, so the box it sits in matches it exactly. */
  readonly ratio: number;
}

export const SPLASH_LANDSCAPE: SplashCut = {
  file: 'splash.webp',
  kind: 'cutout',
  left: 0.29053,
  right: 0.71045,
  top: 0.75629,
  bottom: 0.80312,
  ratio: 1.77580,
};

export const SPLASH_PORTRAIT: SplashCut = {
  file: 'splash-portrait.webp',
  kind: 'drawn',
  left: 0.12000,
  right: 0.88000,
  top: 0.60227,
  bottom: 0.61427,
  ratio: 0.56250,
};

/** The one composed for the shape the screen is now. */
export function splashFor(wide: number, tall: number): SplashCut {
  return wide >= tall ? SPLASH_LANDSCAPE : SPLASH_PORTRAIT;
}
