'use client';
import { Activity, Radio, ShieldAlert, LockKeyhole, ScanLine, Waves } from 'lucide-react';
import BoundaryMap from './BoundaryMap';
import type { StoryScene } from '../data/story';
export default function ConsolePanel({scene,done,camera,line}:{scene:StoryScene;done:string[];camera:string;line:number}) {
 const p=scene.panel;
 if(p==='none')return null;
 const panels:Record<string,{label:string;status:string;body:React.ReactNode}>= {
 security:{label:'Network security',status:done.includes('lock')?'LOCK BYPASSED':'UNAUTHORIZED ACCESS',body:<><div className="terminal-code"><span>network.monitor</span><span className="amber">unknown connection detected</span><span>{done.includes('trace')?'connection lost · trace unavailable':'awaiting trace request'}</span><span>directory / projects / TOMBS</span><span className="cursor-line">{done.includes('lock')?'terminal reopened remotely':'security protocol violation'}<b>▌</b></span></div><div className="system-row"><span>Access logs</span><span>No irregular entries</span></div></>},
 intercom:{label:'Laboratory intercom',status:'VOICE LINK',body:<div className="voice-panel"><Radio/><span>Sarah Bennett</span><div className="voice-bars">{Array.from({length:18},(_,i)=><i key={i} style={{animationDelay:`${i*.1}s`}}/>)}</div><small>Internal laboratory channel</small></div>},
 logs:{label:'Access history',status:'NO ENTRIES',body:<><div className="big-reading">0<span>anomalies recorded</span></div><div className="terminal-code"><span>Session history · clear</span><span>Remote access history · clear</span><span className="amber">“Too clean.”</span></div></>},
 request:{label:'TOMBS initialization',status:done.includes('credentials')?'ACCESS REVOKED':'REMOTE REQUEST',body:<><ShieldAlert className="console-symbol amber"/><h3>Remote initialization</h3><div className="system-row"><span>Administrator</span><span>J. Bennett</span></div><div className="system-row"><span>Authorization</span><span className="amber">{done.includes('credentials')?'REVOKED':done.includes('reject')?'REQUEST DENIED':'NOT GRANTED'}</span></div></>},
 power:{label:'Utility control',status:done.includes('disconnect')?'GRID DISCONNECTED':'ABOVE STANDBY',body:<><div className="big-reading">{done.includes('disconnect')?'—':line>=6?'15':'14'}<span>{done.includes('disconnect')?'array remains active':'MW · grid draw climbing'}</span></div><div className="power-meter"><i/></div><div className="system-row"><span>Internal reactor</span><span>Offline</span></div><div className="system-row"><span>Array supply</span><span className="amber">{done.includes('disconnect')?'Unknown':'Investigating'}</span></div></>},
 array:{label:'TOMBS Array',status:done.includes('shutdown')?'DISCONNECT BYPASSED':'EMITTERS ACTIVE',body:<><div className="ring-monitor"><span/><span/><span/><i/></div><div className="system-row"><span>Boundary emitters</span><span className="amber">Unresponsive</span></div><div className="system-row"><span>Shutdown circuit</span><span>{done.includes('shutdown')?'Physically disconnected':'Manual lever available'}</span></div></>},
 boundary:{label:'Boundary acquisition',status:'TARGET EXCEEDS TEST LIMITS',body:<><BoundaryMap/><div className="system-row"><span>Target dimensions</span><span className="amber">Kilometers</span></div><div className="system-row"><span>Target mass</span><span>Calculating</span></div><div className="system-row"><span>Settlement protocol</span><span>{done.includes('shelter')?'Shelter indoors':'Awaiting instruction'}</span></div></>},
 locked:{label:'TOMBS control',status:scene.id==='locked'?'SCALE FACTOR LOCKED':'BOUNDARY ACQUIRED',body:<><LockKeyhole className="console-symbol amber"/><div className="terminal-code"><span>boundary.acquisition → complete</span><span>scale.factor → {scene.id==='locked'?'locked':'calculating'}</span><span className="amber">manual.control → denied</span><span>emitter.override → no response</span></div></>},
 sensors:{label:'Local sensor grid',status:'SYSTEMS RESPONDING',body:<><Activity className="console-symbol"/><div className="system-row"><span>Temperature</span><span>Normal</span></div><div className="system-row"><span>Pressure & atmosphere</span><span>Normal</span></div><div className="system-row"><span>Structure</span><span>No collapse</span></div><div className="system-row"><span>TOMBS</span><span>Offline</span></div>{scene.id==='tremor'&&<div className="system-row"><span>Seismic event</span><span>None detected</span></div>}</>},
 comms:{label:'Communications',status:'EXTERNAL LINK LOST',body:<><Radio className="console-symbol"/><div className="system-row"><span>Settlement internal</span><span>Available</span></div><div className="system-row"><span>External radio</span><span className="amber">No signal</span></div><div className="system-row"><span>Satellite</span><span className="amber">No signal</span></div><div className="system-row"><span>Beyond boundary</span><span className="amber">Unreachable</span></div></>},
 cameras:{label:'Perimeter surveillance',status:'LOCAL FEED',body:<><ScanLine className="console-symbol"/><h3>{({north:'Northern perimeter',west:'Western road',tree:'Familiar tree',zoom:'Communications building',water:'Southern boundary'} as Record<string,string>)[camera]}</h3><div className="system-row"><span>Camera movement</span><span>Responding</span></div><div className="system-row"><span>Optical zoom</span><span>Minimum · 1×</span></div><div className="system-row"><span>Horizon</span><span>Obscured</span></div></>},
 event:{label:'Final event record',status:'BOUNDARY EVENT COMPLETE',body:<><div className="scale-reveal">1 <em>:</em> 180</div><p className="event-note">The island is unchanged.</p>{done.includes('everyone')?<BoundaryMap complete/>:<div className="system-row"><span>Boundary record</span><span>Available</span></div>}<div className="system-row"><span>Affected region</span><span>Research settlement</span></div>{done.includes('everyone')&&<div className="system-row"><span>Population inside</span><span>~500 people</span></div>}</>},
 };
 const panel=panels[p];if(!panel)return null;
 return <aside className={`console-panel panel-${p}`} aria-label={panel.label}><header><Waves size={17}/><span>TOMBS / {panel.label}</span></header><div className="console-body">{panel.body}</div><footer><span className={`status-dot ${scene.intensity>0?'warning':''}`}/>{panel.status}</footer></aside>;
}
