/**
 * WHAT EVERY DOWNLOAD ACTUALLY WEIGHS, written down at build time.
 *
 * The loading screen declares a total before anything has arrived, and
 * it used to declare a GUESS — 445 KB a band, 2.07 MB for the queen —
 * corrected file by file as each response's Content-Length landed. Two
 * things went wrong with that, and Joshua saw the result: "when I first
 * started the loading it said 5.0mb, but then dropped to 4.6mb".
 *
 * The guesses are individually poor even though they average well:
 * snow.jpg is 143 KB SMALLER than the guess and grass.jpg is 84 KB
 * bigger, so the declared total lurches by a hundred kilobytes and more
 * as files land, in whatever order the browser happens to finish them.
 *
 * And the correction can arrive far too late. fetchBytes only trusts a
 * Content-Length when the response carries no content-encoding — quite
 * right, since the stream yields DECOMPRESSED bytes and the header
 * counts compressed ones — but the consequence is that a compressed
 * response keeps its guess for the whole download and then snaps to the
 * truth at the very end.
 *
 * None of which needs to happen: these files are in the repository, and
 * their sizes are known now. This writes them into the bundle, so the
 * total is right in the first frame and never moves. `resize` still
 * runs and still corrects, but it now has nothing to correct.
 *
 *   npx vite-node scripts/bakeSizes.ts
 *
 * Run it after adding or re-encoding anything the loader waits on.
 * tests/assetSizes.test.ts fails if this file drifts from the folder.
 */
import { statSync, writeFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

/** Everything the loading screen counts, relative to `public/`. */
const COUNTED = [
  ...readdirSync('public/kauai-tex').sort().map((f) => `kauai-tex/${f}`),
  'models/queen-winged.glb',
  'water-normal.png',
  'kauai-wet.bin',
];

const rows = COUNTED.map((path) => `  '${path}': ${statSync(join('public', path)).size},`);
const total = COUNTED.reduce((sum, p) => sum + statSync(join('public', p)).size, 0);

writeFileSync('src/ui/assetSizes.ts', `/**
 * HOW BIG EVERY COUNTED DOWNLOAD IS, in bytes.
 *
 * GENERATED by scripts/bakeSizes.ts — do not edit by hand. Run that
 * script after adding or re-encoding anything the loading screen waits
 * on; tests/assetSizes.test.ts fails if this drifts from public/.
 *
 * It exists so the loading screen can declare a total that is RIGHT in
 * the first frame instead of a guess that lurches as files land. See
 * the script's header for what that looked like.
 *
 * Total: ${(total / 1024 / 1024).toFixed(2)} MB.
 */
export const ASSET_BYTES: Readonly<Record<string, number>> = {
${rows.join('\n')}
};

/** What a file weighs, or null if it was not baked. */
export function assetBytes(path: string): number | null {
  return ASSET_BYTES[path] ?? null;
}
`);
console.log(`${COUNTED.length} files, ${total} B (${(total / 1024 / 1024).toFixed(2)} MB)`);
for (const p of COUNTED) console.log(`  ${p.padEnd(32)} ${statSync(join('public', p)).size}`);
