/**
 * WHAT IS ACTUALLY ON DISK — generated by `npm run bake:sky`.
 *
 * DO NOT EDIT. Re-run the bake.
 *
 * The four skies the dome cross-fades between (`src/sky/SkyView.ts`),
 * each baked once per rung of the texture ladder (`textureQuality.ts`)
 * as an equirectangular, lossy, sRGB WebP — width the rung's size,
 * height half of it. What was MEASURED at bake time is written here
 * beside what was chosen, so a runtime can rotate each image to put its
 * baked sun where the real sun is, and so the exposure a sky was given
 * is a number rather than a memory.
 *
 *   clear   sun az 0.598 el  74.5°  exposure    0.4825  clipped 0.076%
 *           128: 1 KiB, 256: 2 KiB, 512: 4 KiB, 1024: 10 KiB, 2048: 27 KiB
 *   partly  sun az 0.605 el   7.0°  exposure    0.2630  clipped 0.001%
 *           128: 1 KiB, 256: 3 KiB, 512: 8 KiB, 1024: 20 KiB, 2048: 51 KiB
 *   dusk    sun az 0.599 el  11.9°  exposure    0.2009  clipped 0.000%
 *           128: 1 KiB, 256: 1 KiB, 512: 2 KiB, 1024: 5 KiB, 2048: 16 KiB
 *   night   sun az 0.629 el   3.7°  exposure   0.02512  clipped 0.000%
 *           128: 0 KiB, 256: 1 KiB, 512: 2 KiB, 1024: 5 KiB, 2048: 22 KiB
 *
 * What a tier costs. Wire bytes are all four files; a phone loads at
 * most the two the current look reads (`SkyView` releases the rest),
 * and the dome samples with no mip chain — it is only ever magnified —
 * so a resident image is width × height × 4 bytes and no more:
 *
 *   ultra-low   128 ×   64   all four on the wire     3 KiB   one on the GPU    32 KiB   two resident    64 KiB
 *   low         256 ×  128   all four on the wire     6 KiB   one on the GPU   128 KiB   two resident   256 KiB
 *   medium      512 ×  256   all four on the wire    16 KiB   one on the GPU   512 KiB   two resident  1024 KiB
 *   high       1024 ×  512   all four on the wire    41 KiB   one on the GPU  2048 KiB   two resident  4096 KiB
 *   ultra-high 2048 × 1024   all four on the wire   117 KiB   one on the GPU  8192 KiB   two resident 16384 KiB
 *
 * Rungs the bake was offered: 128, 256, 512, 1024, 2048.
 *
 * LICENSES. Every image here is Poly Haven, CC0 (Creative Commons Zero,
 * https://polyhaven.com/license): no attribution required, none
 * withheld — the masters are named by their Poly Haven ids in
 * `art/sky/`. Decoded, exposed (ACES) and encoded by
 * `scripts/bakeSky.mjs`.
 */
import { TEXTURE_QUALITY, type TextureTier } from './textureQuality';

/** The four skies, by what the sky LOOKS like — `skyLook.ts` chooses among them. */
export type SkyImageId = 'clear' | 'partly' | 'dusk' | 'night';

export const SKY_IMAGE_IDS: readonly SkyImageId[] = Object.freeze(['clear', 'partly', 'dusk', 'night']);

export interface BakedSky {
  readonly id: SkyImageId;
  /** The master's file name under `art/sky/`. */
  readonly source: string;
  /** The master's width. Nothing above this is baked. */
  readonly masterWidth: number;
  /** The widths that exist on disk, coarsest first. Height is always half the width. */
  readonly widths: readonly number[];
  /** Where the sun (the brightest thing above the horizon) is: a fraction of the width, 0..1, measured at bake. */
  readonly sunAzimuth: number;
  /** Its elevation, radians above the horizon, measured at bake. */
  readonly sunElevation: number;
  /** The linear exposure multiplier the image was tone-mapped at. */
  readonly exposure: number;
  /** The fraction of pixels that saturated under the curve. */
  readonly clipped: number;
}

/** Where the baked files live, relative to the site root. */
export const SKY_DIR = 'sky';

/** The licence every file in `public/sky/` carries. */
export const SKY_LICENCE = 'Poly Haven, CC0';

const BAKED: readonly BakedSky[] = [
  {
    /** Noon, a high sun and a few thin clouds: the sky of a trade-wind afternoon. */
    id: 'clear',
    source: 'kloppenheim_05_puresky_2k.hdr',
    /** The master's width. Nothing above this was baked. */
    masterWidth: 2048,
    /** The widths that exist on disk, coarsest first. Height is always half. */
    widths: Object.freeze([128, 256, 512, 1024, 2048]),
    /** The brightest thing above the horizon, as a fraction of the width 0..1 — measured at bake. */
    sunAzimuth: 0.59766,
    /** Its elevation, radians above the horizon — measured at bake. */
    sunElevation: 1.30082,
    /** The exposure the sky was baked at: the key (0.2) over the measured median (4.145e-1). */
    exposure: 0.48253,
    /** Fraction of pixels that saturated under the curve — the sun disc, and what it took with it. */
    clipped: 7.644e-4,
  },
  {
    /** A low sun behind broken cloud: what the day sky becomes as cover builds. */
    id: 'partly',
    source: 'kloppenheim_06_puresky_2k.hdr',
    /** The master's width. Nothing above this was baked. */
    masterWidth: 2048,
    /** The widths that exist on disk, coarsest first. Height is always half. */
    widths: Object.freeze([128, 256, 512, 1024, 2048]),
    /** The brightest thing above the horizon, as a fraction of the width 0..1 — measured at bake. */
    sunAzimuth: 0.60547,
    /** Its elevation, radians above the horizon — measured at bake. */
    sunElevation: 0.12272,
    /** The exposure the sky was baked at: the key (0.15) over the measured median (5.704e-1). */
    exposure: 0.26299,
    /** Fraction of pixels that saturated under the curve — the sun disc, and what it took with it. */
    clipped: 5.245e-6,
  },
  {
    /** Dusk, the sun just under the horizon and the warmth going out of the sky. */
    id: 'dusk',
    source: 'qwantani_dusk_2_puresky_2k.hdr',
    /** The master's width. Nothing above this was baked. */
    masterWidth: 2048,
    /** The widths that exist on disk, coarsest first. Height is always half. */
    widths: Object.freeze([128, 256, 512, 1024, 2048]),
    /** The brightest thing above the horizon, as a fraction of the width 0..1 — measured at bake. */
    sunAzimuth: 0.59894,
    /** Its elevation, radians above the horizon — measured at bake. */
    sunElevation: 0.20686,
    /** The exposure the sky was baked at: the key (0.16) over the measured median (7.962e-1). */
    exposure: 0.20094,
    /** Fraction of pixels that saturated under the curve — the sun disc, and what it took with it. */
    clipped: 0.000e+0,
  },
  {
    /** Night: stars, the Milky Way, and enough glow to tell the horizon from the ground. */
    id: 'night',
    source: 'qwantani_night_puresky_2k.hdr',
    /** The master's width. Nothing above this was baked. */
    masterWidth: 2048,
    /** The widths that exist on disk, coarsest first. Height is always half. */
    widths: Object.freeze([128, 256, 512, 1024, 2048]),
    /** The brightest thing above the horizon, as a fraction of the width 0..1 — measured at bake. */
    sunAzimuth: 0.62859,
    /** Its elevation, radians above the horizon — measured at bake. */
    sunElevation: 0.06452,
    /** The exposure the sky was baked at: the key (0.012) over the measured median (4.776e-1). */
    exposure: 0.025123,
    /** Fraction of pixels that saturated under the curve — the sun disc, and what it took with it. */
    clipped: 0.000e+0,
  },
];

export const BAKED_SKIES: readonly BakedSky[] = Object.freeze(BAKED.map((s) => Object.freeze(s)));

export function bakedSky(id: SkyImageId): BakedSky {
  const found = BAKED_SKIES.find((s) => s.id === id);
  if (!found) throw new Error(`no baked sky named ${id}`);
  return found;
}

/**
 * The width this sky actually has for a tier: the tier's rung, or the
 * largest smaller one when the master could not reach it. Clamps DOWN,
 * never up, and never throws — exactly `textureManifest.textureSizeFor`.
 */
export function skyWidthFor(id: SkyImageId, tier: TextureTier): number {
  const { widths } = bakedSky(id);
  const want = TEXTURE_QUALITY[tier].size;
  let best = widths[0];
  for (const width of widths) if (width <= want && width > best) best = width;
  return best;
}

/** The URL to load, built in one place so nothing spells a path by hand. */
export function skyUrl(id: SkyImageId, tier: TextureTier, base = '/'): string {
  return `${base}${SKY_DIR}/${id}-${skyWidthFor(id, tier)}.webp`;
}
