/**
 * WHAT IS ACTUALLY ON DISK — generated by `npm run bake:textures`.
 *
 * DO NOT EDIT. Re-run the bake.
 *
 * The ladder (`textureQuality.ts`) is the DECISION: five rungs and what
 * each is for. This is the FACT: which textures were baked, at which of
 * those rungs, from a master of what size. They are not the same list and
 * must not be assumed to be — a master smaller than a rung is not baked
 * to that rung, because upscaling invents pixels and then charges the GPU
 * four times the memory for them.
 *
 * So a loader asks `textureUrl`, which walks DOWN from the tier the
 * player chose to the best rung this texture actually has. Nothing builds
 * a path by hand.
 *
 *   water-normal   master 1536, 128: 33 KiB, 256: 148 KiB, 512: 628 KiB, 1024: 2484 KiB
 *   surf-foam      master 1024, 128: 7 KiB, 256: 26 KiB, 512: 107 KiB, 1024: 380 KiB
 *
 * Rungs the bake was offered: 128, 256, 512, 1024, 2048.
 */
import { TEXTURE_QUALITY, type TextureTier } from './textureQuality';

/** How a texture must be encoded — see `scripts/bakeTextures.mjs`. */
export type TextureKind = 'normal' | 'colour';

export type TextureName = 'water-normal' | 'surf-foam';

export interface BakedTexture {
  readonly name: TextureName;
  readonly kind: TextureKind;
  /** The master's own size. Nothing above this is baked. */
  readonly masterSize: number;
  /** The rungs that exist on disk, coarsest first. */
  readonly sizes: readonly number[];
}

/** Where the baked files live, relative to the site root. */
export const TEXTURE_DIR = 'tex';

const BAKED: readonly BakedTexture[] = [
  {
    /** The ripple normal map. The ocean shader samples it four times at four scales, twice over, so it is the most-read texture in the game. */
    name: 'water-normal',
    kind: 'normal',
    /** The master's own size. Nothing above this was baked. */
    masterSize: 1536,
    /** The rungs that exist on disk, coarsest first. */
    sizes: Object.freeze([128, 256, 512, 1024]),
  },
  {
    /** Foam, read as a brightness where the wave has broken. */
    name: 'surf-foam',
    kind: 'colour',
    /** The master's own size. Nothing above this was baked. */
    masterSize: 1024,
    /** The rungs that exist on disk, coarsest first. */
    sizes: Object.freeze([128, 256, 512, 1024]),
  },
];

export const BAKED_TEXTURES: readonly BakedTexture[] = Object.freeze(BAKED.map((t) => Object.freeze(t)));

export function bakedTexture(name: TextureName): BakedTexture {
  const found = BAKED_TEXTURES.find((t) => t.name === name);
  if (!found) throw new Error(`no baked texture named ${name}`);
  return found;
}

/**
 * The size this texture actually has for a tier: the tier's rung, or the
 * largest smaller one when the master could not reach it.
 *
 * CLAMPS DOWN, NEVER UP, and never throws. A player on ULTRA HIGH must
 * not get a missing texture because one master happened to be 1536
 * across; they get the best that exists, which is what "high" means for
 * that texture.
 *
 * The downward direction is guaranteed rather than hoped for: the bake
 * refuses a master smaller than the COARSEST rung, so `sizes[0]` is
 * always that rung and every tier's size is at least it.
 */
export function textureSizeFor(name: TextureName, tier: TextureTier): number {
  const { sizes } = bakedTexture(name);
  const want = TEXTURE_QUALITY[tier].size;
  let best = sizes[0];
  for (const size of sizes) if (size <= want && size > best) best = size;
  return best;
}

/** The URL to load, built in one place so nothing spells a path by hand. */
export function textureUrl(name: TextureName, tier: TextureTier, base = '/'): string {
  return `${base}${TEXTURE_DIR}/${name}.${textureSizeFor(name, tier)}.webp`;
}
